### PR TITLE
Clean up docker-compose and k8s scripts

### PR DESCRIPTION
**Pull request by rekt0x**

### CODE REVIEW

**Comment by rekt0x** [comment]
The idea is to combine both chaosnet and testnet setup scripts (not really necessary to explicitly have both if you can just modify the values). I also merged both k8s setup scripts into one script, so both the pvc and the deployment will get created at once.

**Review by mr-rooftop — CHANGES_REQUESTED** [review]
It makes sense to have a single setup File for Kubernetes, as you for sure have a different cluster per network.

It doesn't make sense to have a single docker-compose.yaml, because node operators will need to modify a lot of fields for each network (chaosnet, testnet, etc).

I even feel like that it's better to have two K8s yamls, because then a node operator doesn't need to change the yaml each time he wants to connect to a different cluster/network.

I feel like that this PR is cool from a readability perspective, but not from a usability perspective.

**Comment by mbartn** [comment]
How do we proceed with this PR? @rekt0x @mr-rooftop

**Comment by rekt0x** [comment]
Not important right now.

**Pull request closed without merging**
